histomicsui/web_client/panels/AnnotationSelector.js
histomicsui/web_client/templates/panels/annotationSelector.pug
histomicsui/web_client/views/body/ImageView.js

Hide new annotation butter when the user doesn't have permission to use it.

Port HistomicsTK PR 812.

---

tests/web_client_specs/annotationSpec.js
tests/web_client_specs/huiTest.js

This fails occasionally due to timing issues.  These changes should help.

Harden the annotationSpec test

---

histomicsui/__init__.py

Internally, cookies are parsed by Girder using python's built-in http.cookies modules (or a backport of that module in Python 2).  This module is conformant to RFC specifications on cookies.  Some non-conformant processes can set cookies that do not parse with this module.  Specifically, in the field we've see cookies like "KEY=part1 part2" with a space in their value.  When the Python module finds particular types of invalid cookies, it refuses to parse any cookies.  This prevents Girder from working as expected.
This fix allows spaces to be in the cookie values and works around the immediate problem.  I think this shouldn't cause any risk, and will allow Girder to work in situations where it would otherwise fail.

Work around some invalid cookies.

---

histomicsui/rest/hui_resource.py
histomicsui/web_client/views/itemPage.js

This allows them to be used by other processes.

Move quarantine processes to separate functions.

---

histomicsui/web_client/panels/OverviewWidget.js
tests/web_client_specs/overviewPanelSpec.js

Only allow drag panning when in or near the outline in the overview.

Limit area where drag panning is allowed.

---

tox.ini

This is now handled in flake8 proper.

Remove flake8-blind-except.

---

histomicsui/__init__.py

Before, this didn't always maintain all of the properties needed and did not rebind class methods.  As a result, it mostly worked but occasionally would have a conflict which would prevent a download even when it should have been allowed.
This should fix https://github.com/DigitalSlideArchive/HistomicsTK/issues/879.

Fix restricting download endpoints.

---

histomicsui/web_client/dialogs/editRegionOfInterest.js
histomicsui/web_client/panels/OverviewWidget.js
histomicsui/web_client/panels/ZoomWidget.js
setup.py

Also, download the correct frame via the zoom widget.

Show the correct frame in the overview panel.

---

histomicsui/web_client/panels/DrawWidget.js
histomicsui/web_client/stylesheets/popover/annotationContextMenu.styl
histomicsui/web_client/templates/body/image.pug
histomicsui/web_client/templates/popover/annotationContextMenu.pug
histomicsui/web_client/views/body/ImageView.js
histomicsui/web_client/views/popover/AnnotationContextMenu.js
tests/web_client_specs/annotationSpec.js

You can edit an element by accessing the context menu and selecting "Edit Shape" or hovering over an element and typing the "E" hotkey.

Support editing annotation elements.

---

histomicsui/web_client/dialogs/editRegionOfInterest.js
histomicsui/web_client/package.json
histomicsui/web_client/panels/AnnotationSelector.js

If the default encoding is set for tiles, it could conflict with the download encoding.

Merge download parameters.

---

histomicsui/web_client/main.js
histomicsui/web_client/views/HierarchyWidget.js

This also increase the default item paging from 100 to 250.

Default to using pagination in item lists.

---

histomicsui/web_client/stylesheets/panels/drawWidget.styl
histomicsui/web_client/templates/panels/drawWidget.pug
histomicsui/web_client/views/popover/AnnotationPopover.js
requirements-dev.txt
setup.py

Add controls for ellipse and circle annotations

Ellipse and circle annotations

---

histomicsui/web_client/views/body/ImageView.js
tests/web_client_specs/analysisSpec.js

Better clear tooltips.

---

histomicsui/rest/image_browse_resource.py

Explicitly order next and previous item buttons

---

histomicsui/__init__.py
histomicsui/constants.py
histomicsui/handlers.py
histomicsui/web_client/templates/body/configView.pug
histomicsui/web_client/views/body/ConfigView.js

All the data is present in the annotation database.

Add an option to remove annotation files after ingest.

---

histomicsui/rest/system.py
tests/test_hui_rest.py

This isn't in use yet and has been superseded by https://github.com/girder/large_image/pull/860 which has better support for users and groups.

Remove the json config route.

---

histomicsui/rest/system.py

This makes development easier.  We might want to only expose it in development mode.

Add an endpoint to restart the system.

---

histomicsui/web_client/panels/DrawWidget.js
histomicsui/web_client/templates/panels/drawWidget.pug
histomicsui/web_client/templates/panels/drawWidgetElement.pug

Speed up adding annotation elements.

---

histomicsui/web_client/panels/DrawWidget.js
histomicsui/web_client/views/body/ImageView.js

The bound context would be for a previous draw widget.

Fix an issue when switching annotations and editing.

---

histomicsui/web_client/panels/DrawWidget.js

This affects how we convert ellipses to polygons.
This also fixes a bug where if a non-brush annotation was created before a brush annotation, the annotation layer would stop tracking pan changes for adjusting the renderer's camera matrix.

Use a screen-relative pixel tolerance.

---

histomicsui/web_client/views/itemList.js

This makes it easier to reuse with different templates.

Refactor how controls are found and modified.

---

histomicsui/__init__.py

Use the last Girder build time to appropriately reload javascript and css for the Girder and HistomicsUI web interfaces.
This is something I wish was in Girder core.  Without it, we have to make sure people do a hard reload of their browser after updating the software.  With it, a regular reload is sufficient.

Better invalidate JS and CSS caches.

---

docs/config_options.rst
histomicsui/web_client/dialogs/editElement.js
histomicsui/web_client/dialogs/editStyleGroups.js
histomicsui/web_client/panels/AnnotationSelector.js
histomicsui/web_client/panels/DrawWidget.js
histomicsui/web_client/templates/panels/drawWidgetElement.pug
histomicsui/web_client/views/body/ImageView.js
histomicsui/web_client/views/popover/AnnotationContextMenu.js
tests/test_files/.histomicsui_config.yaml
tests/test_web_client.py
tests/web_client_specs/annotationSpec.js
tests/web_client_specs/huiTest.js

Closes #42, #21.
See docs for details.
This could use some tests.

Support changing annotation groups based on a config file.

---

histomicsui/web_client/vue/components/EditHeatmapOrGridData.vue

No colors is a valid option.  Use appropriate defaults.

Harden heatmap dialog.

---

histomicsui/web_client/dialogs/saveAnnotation.js
histomicsui/web_client/stylesheets/dialogs/saveAnnotation.styl
histomicsui/web_client/templates/dialogs/saveAnnotation.pug

This is in the edit annotation dialog.
Closes #212.

Show annotation created and updated times and the annotation id.

---

docs/config_options.rst
histomicsui/__init__.py

Also, document the girder setting.

Optionally relax restricting downloads for small files.

---

histomicsui/web_client/package.json

It won't work with tests in newer versions without changes.

Pin tinycolor2

---

histomicsui/web_client/views/itemList.js

This uses fewer function calls when updating for the quarantine control.

Speed up item list updates.

---

README.rst

@annehaley I believe these instruction now will get you a working instance with some tile sources.

Update the readme.

---

histomicsui/web_client/panels/DrawWidget.js
histomicsui/web_client/views/popover/AnnotationContextMenu.js

When changing the group from the context menu of one or more elements, the element list wasn't updated.

Fix a bug where elements wouldn't update immediately.

---

histomicsui/web_client/panels/FrameSelectorWidget.js
histomicsui/web_client/stylesheets/panels/frameSelectorWidget.styl
histomicsui/web_client/templates/body/image.pug
histomicsui/web_client/templates/panels/frameSelectorWidget.pug
histomicsui/web_client/views/body/ImageView.js
tests/web_client_specs/panelLayoutSpec.js

This needs css work before it can be merged.

Expose the frame selector as a new panel

---

histomicsui/web_client/collections/UserCollection.js
histomicsui/web_client/collections/index.js

This avoids getting 401 errors; it just won't ask to get users.

Don't attempt to fetch user collections if anonymous.

---

histomicsui/web_client/webpack.helper.js

This also will allow it to work with npm >= 8.

Simplify a path resolution in the webpack helper file

---

docs/controls.rst
histomicsui/web_client/package.json
tests/datastore.py

Tweak some spacing.

---

histomicsui/web_client/dialogs/saveAnnotation.js
histomicsui/web_client/panels/AnnotationSelector.js
histomicsui/web_client/stylesheets/dialogs/saveAnnotation.styl
histomicsui/web_client/templates/dialogs/saveAnnotation.pug
setup.py

Support default annotation visibility.

---

docs/config_options.rst
histomicsui/web_client/panels/MetadataWidget.js
histomicsui/web_client/views/body/ImageView.js

Allow panels to be configure via .histomicsui_config.yaml.

---

docs/config_options.rst
histomicsui/web_client/stylesheets/layout/layout.styl
histomicsui/web_client/views/body/ImageView.js

This is a hacky implementation of dark mode and should have much more css to make it right.

Configurable dark mode

---

docs/config_options.rst
histomicsui/web_client/panels/AnnotationSelector.js

Make some settings on the annotation panel configurable.

---

histomicsui/handlers.py
histomicsui/rest/system.py
histomicsui/web_client/stylesheets/panels/frameSelectorWidget.styl

Handle deprecations for Python 3.12

Update max-merge css for frame selector

---

histomicsui/web_client/dialogs/metadataPlot.js
histomicsui/web_client/panels/MetadataPlot.js
histomicsui/web_client/templates/dialogs/metadataPlot.pug

Support violin plots in the Metadata Plot panel

---

histomicsui/webroot.mako

Add a semicolon for consistency

Adjust formatting

---

histomicsui/web_client/panels/DrawWidget.js
histomicsui/web_client/views/popover/AnnotationContextMenu.js

Hitting escape while drawing a polygon annotation left the draw tool in an odd state.
This also resolves #378.

Harden drawing annotations.

---

.pre-commit-config.yaml
histomicsui/web_client/package.json
histomicsui/web_client/panels/MetadataPlot.js
histomicsui/web_client/templates/dialogs/metadataPlot.pug
histomicsui/web_client/webpack.helper.js
tests/test_web_client.py

Pull plotly package as part of the build process rather than on-demand so that it loads faster

Use new plottable data endpoints from large_image

---

.pre-commit-config.yaml
histomicsui/web_client/stylesheets/layout/headerAnalyses.styl
histomicsui/web_client/templates/layout/headerAnalyses.pug
histomicsui/web_client/views/layout/HeaderAnalysesView.js
tests/test_tcga.py

This mostly resolves #409.  There are still issues when there are lots of versions, lots of clis, or narrow windows.

Better handle long analyses menu

---

histomicsui/web_client/views/itemList.js
setup.py

This requires an appropriately new version in large_image.
Future work is to support app icons.  Those should probably be configurable before any are merged in.

Add and support app buttons.

---

histomicsui/web_client/panels/MetadataPlot.js
tox.ini

If no symbol was set, setting the title would throw an exception

Fix an issue with violin plot x-axis titles

---

histomicsui/web_client/panels/FrameSelectorWidget.js
histomicsui/web_client/stylesheets/panels/frameSelectorWidget.styl
setup.py

This is needed with the refactor in https://github.com/girder/large_image/pull/1738.

Updates for large_image frame selector differences.

---

histomicsui/web_client/models/StyleModel.js

Make sure style groups can't hold invalid keys

Add PR #456 to girder-5

---

histomicsui/web_client/panels/ZoomWidget.js
histomicsui/web_client/stylesheets/panels/zoomWidget.styl
histomicsui/web_client/templates/panels/zoomWidget.pug

Zoom input

---

histomicsui/web_client/vite.config.ts

The browser is requesting the favicon on every route change, even when we only change the fragment.  This is different from Girder-3, probably because of something that babel did in the webpack build.  I tried a variety of solutions to prevent constantly re-requesting the favicon, but this was the only one I found that actually worked reliably.

Inline the favicon as part of the vite build

---

histomicsui/web_client/package-lock.json
histomicsui/web_client/package.json
histomicsui/web_client/tests/server.ts
requirements-dev.txt
setup.py
tox.ini

Update girder-5 version

---

histomicsui/web_client/dialogs/openAnnotatedImage.js
histomicsui/web_client/templates/dialogs/annotatedImageList.pug

Fix the api root of recently annotated images
