DigitalSlideArchive/HistomicsUI

- histomicsui/__init__.py
- histomicsui/constants.py
- tests/test_hui_rest.py
Add a setting allowing a comma-separate list of alternate webroot paths.  This facilitates migrating to a new webroot path by allowing old paths to still work.
This will help resolve https://github.com/DigitalSlideArchive/digital_slide_archive/issues/70
> Allow optional alternate webroot paths.

- histomicsui/rest/hui_resource.py
- histomicsui/web_client/package.json
- histomicsui/web_client/views/body/ConfigView.js
- histomicsui/web_client/views/itemList.js
- histomicsui/web_client/views/itemPage.js
- histomicsui/web_client/views/utils.js
- tests/test_web_client.py
- tests/web_client_specs/girderUISpec.js
- tests/web_client_specs/itemSpec.js
Updated the BrandName display in the item view (Open in {BrandName}) to reflect brand name set in the plugin settings.  Updated link to go to the correct webroot_path also set in the plugin settings.  These settings are now public settings that are accessible through the histomicsui/settings endpoint.
Add a utils.js to the views with a single HUISettings tool for caching settings.  Used a name export for any needed future utilities.
Added an additional itemSpec test, to change the webroot_path and brandname and confirm the changes in the itemview.  This may overlap the girderUISpec.js test which confirms that an Open in HistomicsUI button and the quarantine button exist.  So it can possibly be rolled into one test in the future.
> Brand name update

- histomicsui/web_client/views/itemList.js
Some code to prevent double quarantine buttons wasn't working.
It would probably be better not to do a remove-and-reinsert, but this is a minimal change.
> Fix showing double quarantine buttons.

- histomicsui/web_client/dialogs/openAnnotatedImage.js
- histomicsui/web_client/dialogs/openImage.js
This uses new browser widget features and works with virtual folders.
This also gets all users and root items, rather than an arbitrary number.  When there are more users or root items than the arbitrary limit, there was no indication that not all items were loaded.  Here, an excessive number of users or collections could break the UI, but this is unlikely to happen and would at least be an obvious problem instead of appearing to have missing data.
> Start at the last image in the browser widget.

- histomicsui/web_client/dialogs/editStyleGroups.js
- histomicsui/web_client/views/popover/AnnotationPopover.js
This also shows perimeter of polygons and lengths of line annotations.  Most values are shown in both pixels and SI units.
> Show area on annotation popover.

- setup.py
This is needed for girder-worker.
> Pin diskcache on Python 2.7.

- histomicsui/handlers.py
- histomicsui/rest/hui_resource.py
This makes it easier to override in downstream plugins.
> Move the quarantine code from rest to handlers.

- histomicsui/__init__.py
- histomicsui/constants.py
- histomicsui/rest/hui_resource.py
- histomicsui/web_client/panels/AnnotationSelector.js
- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/panels/MetadataWidget.js
- histomicsui/web_client/panels/ZoomWidget.js
- histomicsui/web_client/stylesheets/body/image.styl
- histomicsui/web_client/templates/body/configView.pug
- histomicsui/web_client/templates/body/image.pug
- histomicsui/web_client/views/body/ConfigView.js
- histomicsui/web_client/views/body/ImageView.js
- histomicsui/web_client/views/utils.js
- tests/test_hui_rest.py
- tests/test_web_client.py
- tests/web_client_specs/panelLayoutSpec.js
This adds a setting which takes a json list.  Each entry in the list consists of a dictionary with the name of a panel (using short internal names), and, optional position and state.  The title (tooltip) text on the setting lists the options.
> Support a panel layout setting.

- histomicsui/web_client/panels/OverviewWidget.js
- histomicsui/web_client/stylesheets/panels/overviewWidget.styl
- histomicsui/web_client/templates/body/image.pug
- histomicsui/web_client/templates/panels/overviewWidget.pug
- histomicsui/web_client/views/body/ImageView.js
- tests/test_web_client.py
- tests/web_client_specs/overviewPanelSpec.js
- tests/web_client_specs/panelLayoutSpec.js
Add controls to the overview.  Clicking recenters to that point.  Shift-left drag zooms to the selected rectangle (and unrotates).  Left drag pans.
There may be better controls.  Perhaps the left drag control shouldn't operate unless started in the view rectangle.  The view rectangle could have annotation-like handles.  The mouse wheel and pinch gestures could do zoom and rotate (and, if so, should zoom be animated)?
Closes #15.
> Add an image overview panel.

- histomicsui/web_client/panels/OverviewWidget.js
If the overview panel is collapsed and is asked to rerender, the map ended up being 512 pixels wide.  There were two separate effects that could result in this behavior.  When a new analysis task is loaded, the overview panel has the tile source updated, even though it didn't change.  Any such update resulted in recreating the map unnecessarily.
When the map was created, if the div for the map was not visible due to being collapsed, it has a zero width.  geojs defaults to 512 pixels wide in this case.  Further, if the div changed size without the window changing size, that map was not updated appropriately (for instance, when the scroll bar appears or disappears).  Use a ResizeObserver, if available, to adjust the map when either condition occurs.
> Prevent invalid overview resizing.

- .circleci/config.yml
- .travis.yml
- README.rst
- requirements-dev.txt
- setup.py
- tox.ini
They are both end-of-life.
Closes #89.
> Drop support for Python 2.7 and 3.5.

- histomicsui/web_client/views/body/ImageView.js
If you open an image, select an analysis, then close the analysis panel and switch to another image, the analysis panel would reappear.
> Fix analysis panel not staying closed.

- histomicsui/web_client/dialogs/index.js
- histomicsui/web_client/dialogs/metadataPlot.js
- histomicsui/web_client/panels/MetadataPlot.js
- histomicsui/web_client/panels/MetadataWidget.js
- histomicsui/web_client/stylesheets/body/frontPage.styl
- histomicsui/web_client/stylesheets/layout/layout.styl
- histomicsui/web_client/stylesheets/panels/metadataPlot.styl
- histomicsui/web_client/stylesheets/panels/metadataWidget.styl
- histomicsui/web_client/templates/body/image.pug
- histomicsui/web_client/templates/dialogs/metadataPlot.pug
- histomicsui/web_client/templates/panels/metadataPlot.pug
- histomicsui/web_client/templates/panels/metadataWidget.pug
- histomicsui/web_client/templates/panels/panel.pug
- histomicsui/web_client/views/body/ImageView.js
- tests/test_web_client.py
- tests/web_client_specs/metadataPlotSpec.js
- tests/web_client_specs/panelLayoutSpec.js
If metadata exists in the form key: array of objects, and the first element of such an array has numerical values, then the option to plot the data, possibly with data from sibling items in the same folder is presented.  This pulls plotly from a CDN if needed.  If the current item's metadata doesn't allow for a plot, no extra http requests are made.
Use closest hovermode in plotly.  The default hovermode is unintuitive.  
Add axis titles when the graph is maximized.
Added a control for maximizing the plot size.
> Add a metadata plot panel.

- histomicsui/web_client/stylesheets/panels/zoomWidget.styl
This allows high zoom values to not enlarge the control before it is necessary.
> Adjust zoom control padding.

- histomicsui/__init__.py
- setup.py
- tox.ini
Projects that don't use slicer_cli_web jobs shouldn't be required to install all of the dependencies for it.
> Make analysis an extra_requires.

- histomicsui/web_client/views/body/ImageView.js
Recent [changes](https://github.com/girder/large_image/pull/750) to the `large_image` girder plugin allowed for image overlay annotations. With those changes, the default behavior for the underlying `geojs` map is to unclamp bounds while image overlays are drawn on the base image. This allows for panning to image overlays that are drawn off of the base image, but removes the ability to scroll out to center the base image.
For HistomicsUI, we will keep the `geojs` map bounds clamped to the base image. This preserves the usability gained from scroll out to center.
> Clamp image viewer bounds, even with overlays

- setup.py
- tox.ini
In a development environment, we may expect that this exists.
> Add setuptools_scm to the tox requirements.

- histomicsui/handlers.py
- histomicsui/rest/system.py
- tests/girder_utilities.py
- tests/test_hui_rest.py
This starts at a given directory and walks up until it finds an appropriate file.  If it reaches the user or collection, it looks in a ".config" folder for such a file.  Specifically, it tries the first file in an item with the specified name.
> Add an endpoint to find a json config file.

- histomicsui/web_client/dialogs/saveAnnotation.js
- histomicsui/web_client/views/View.js
This PR changes the behavior of the Bootstrap `modal` component to automatically close on `mousedown` instead of on `click`.
The latter is the default behavior of Bootstrap, so I attached a new event listener to accomplish this - see code comments for details.
Fixes #140
> Don't close dialog when dragging outside of it

- histomicsui/web_client/views/View.js
This reverts commit 4e591ebec3a2971b6e2333fe22836e4072a99031.
Revert "Use `mousedown` event instead of `click` for auto-closing modal"
This reverts commit 703e7338e9702bc379f9c6c767aa286ce50f1860.
This reopens #140 and closes #150.
> Revert "Generalize the `mousedown` behavior for all modals"

- histomicsui/web_client/views/View.js
@manthey this line was what broke some dialog boxes -
```javascript
dialogContainer.off('click');
```
When jQuery's `.off` method only receives one argument, it removes that event listener from the element it is called on and _also_ all of its children. So what was happening was that line was removing the `click` event listeners from the buttons within the dialogs too. `.off` takes a second argument that lets you specify a specific selector to remove the event listener from. I've done that here -
```javascript
dialogContainer.off('click', '#g-dialog-container');
```
So now it removes the `click` event listener from `#g-dialog-container` only, and not any of its children. I tested all of the dialogs I could find in the UI with this change, and it seems to work fine.
Fixes #140
> Don't close dialog when dragging outside of it (take 2)

- histomicsui/web_client/templates/panels/annotationSelector.pug
- histomicsui/web_client/templates/panels/drawWidget.pug
- histomicsui/web_client/views/body/ImageView.js
- tests/web_client_specs/annotationSpec.js
Pressing `n` will 
- Open the New Annotation dialog if no annotations are selected
- Put the user into or cancel "draw mode" for the current annotation if one is selected
Fixes in part #145
> Add keyboard shortcut to start/stop drawing annotation

- histomicsui/web_client/views/body/ImageView.js
Fixes part of #145.
Hitting the enter key while drawing a polygon or line will automatically save the annotation (and in the case of a polygon, close it properly).
> Add keyboard shortcut for saving polygon/line annotations

- histomicsui/web_client/views/View.js
Adds an event listener that sets `tabindex=0` on all `.btn` elements whenever a new dialog is rendered.
Closes #145
> Set `tabindex` of all dialog buttons

- histomicsui/web_client/templates/layout/header.pug
This prevents the filename from bleeding below it, which is hard to read.
> Specify a background color for the brand in the title bar

- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/views/body/ImageView.js
- tests/web_client_specs/annotationSpec.js
You can hold down shift / ctrl / shift+ctrl / shift+alt when drawing an annotation to combine it with existing annotation elements of the same group and annotation.
> Handle annotation boolean operations

- histomicsui/web_client/stylesheets/views/itemList.styl
- histomicsui/web_client/views/itemPage.js
Makes it more convenient to view a selected image in the Histomics UI by moving the option from the 'Action' menu to it's own separate button.
Addresses #146
> Replace the 'Open in Histomics UI' menu item with a button

- histomicsui/web_client/views/itemList.js
Makes it more convenient to view an image in the Histomics UI by creating a new option to open an image in the UI directly from the hierarchy widget (where items are listed).  The link is located directly to the right of the "View in browser" icon and is an open external link icon with an "Open in HistomicsUI" tooltip.
Closes #146
> Create links from hierarchy widget to images in Histomics UI

- histomicsui/web_client/stylesheets/popover/annotationPopover.styl
Changes style settings so long annotation label titles no longer overflow outside of the popover, but wrap to the next line instead.
Closes #177
> Make long image annotation label titles wrap properly

- histomicsui/web_client/stylesheets/popover/annotationPopover.styl
- histomicsui/web_client/views/popover/AnnotationPopover.js
Until the mouse moves, the popover can me mislocated.  The z-index was below the panels.
> Fix initial popover position.

- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/stylesheets/panels/drawWidget.styl
- histomicsui/web_client/templates/panels/drawWidgetElement.pug
- histomicsui/web_client/views/body/ImageView.js
Adds a new button in 'Interactive Mode' which centers the highlighted annotation on screen by changing the image viewer's zoom and location.  It appears next to an annotation's type when it is moused over in the list.
Closes #33
> Add feature to zoom to highlighted annotations in 'Interactive Mode'

- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/stylesheets/panels/drawWidget.styl
- histomicsui/web_client/templates/panels/drawWidget.pug
- histomicsui/web_client/views/body/ImageView.js
Closes #147.
Closes #141.  The current style group and brush settings are stored in local storage.
Currently, circle and ellipse annotations are converted to polygons when they are combined in some manner.  This could be done in a coarser manner to reduce the number of vertices.  The current setting is no more than 1/10th of a pixel of error at the maximum zoom level (typically this is twice the resolution of the base image, so 1/20th of a base image pixel, though that can be increased).  Perhaps something like 1/2 of a base pixel would be sufficient and speed up some of the processes.
Also, this currently becomes slow with a large number of annotation elements because it updates the entire annotation feature.  To speed this up, we probably would need to render the annotation as two sets …
> Add brush controls

- histomicsui/web_client/package.json
The latest vue 2.x, vue-template-compiler, and vue-loader aren't working with the rest of our stack.
@naglepuff I'm merging this, but if you can take a look at how we can unpin this, I'd appreciate it.
> Pin vue and vue-template-compiler.

- histomicsui/rest/system.py
- histomicsui/web_client/views/body/ConfigView.js
Quite a long time ago, Girder removed the ability to ask for the default settings, which made the default buttons in the plugin settings page not work as intended.  This fixes that.
> Add an endpoint to get default settings.

- histomicsui/web_client/vue/components/ColorPickerInput.vue
Resolves #183 
Previously, in the Vue component for editing heatmap and griddata elements, the color picker could end up being cut off if there wasn't enough room above or below the control.
This PR changes the component so the color picker shows to the side of the control, instead of above or below it.
> Show color picker to the side

- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/stylesheets/panels/drawWidget.styl
- histomicsui/web_client/templates/panels/drawWidget.pug
> Add dropdown to enable drawing shapes with fixed aspect ratios/sizes

- histomicsui/__init__.py
- histomicsui/constants.py
- histomicsui/web_client/stylesheets/body/configView.styl
- histomicsui/web_client/stylesheets/layout/header.styl
- histomicsui/web_client/templates/body/configView.pug
- histomicsui/web_client/templates/layout/header.pug
- histomicsui/web_client/views/body/ConfigView.js
- histomicsui/web_client/views/layout/HeaderView.js
- histomicsui/webroot.mako
Adds an optional help button to the header of HistomicsUI (at the far right) as well as the ability to change the URL it leads to and its tooltip via the HistomicsUI plugin settings.
Closes #193
> Add optional help button

- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/templates/panels/drawWidgetElement.pug
- histomicsui/web_client/views/popover/AnnotationContextMenu.js
Counts the number of cells within a pixelmap that belong to each annotation group and adds the totals to the existing count for individual elements.  Also updates the count when changes are made to the groups of the cells within the pixelmap or when the pixelmap is deleted.
Closes #200
> Add internal pixelmap count to annotation/group count

- histomicsui/web_client/views/body/ImageView.js
This issue was already discussed in #125 and it's almost urgent to have it, according to our labeling experience. Especially, when point annotations are required. This safety buffer is even more important if tablets and stylus pens are used. It greatly reduces the number of missed annotations to almost 0. It's a quick fix and maybe a dirty fix, but it does the job according to our field tests.
> Click buffer of 10px - missing annotations

- tox.ini
This allows pip to resolve working versions correctly.
> Allow flake8 to be an implied dependency.

- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/templates/panels/drawWidgetElement.pug
- tests/web_client_specs/annotationSpec.js
Resolves #195 
This PR creates more descriptive element labels for annotations listed in the draw widget. In addition to the element type, for point, rectangle, ellipse, circle and polyline elements, the group name of the element and a number is added to the element label. 
If an element is assigned a new group when edited, the label is updated to reflect the new group. 
The number corresponding to each element is just a counter that starts at 1 and counts up for each element in the annotation. It is not a long-term ID for the element, and more of a way to more easily differentiate between two elements in the list. New elements added to the annotation (e.g. by being drawn on) are assigned a number as well. When the page is refreshed, the numbers are recalculated. This design might not be …
> Add more descriptive element labels

- histomicsui/web_client/dialogs/saveAnnotation.js
- histomicsui/web_client/panels/AnnotationSelector.js
- histomicsui/web_client/templates/panels/annotationSelector.pug
Uses the new annotation creation access flag and endpoint from PR [#937](https://github.com/girder/large_image/pull/937) in [girder/large_image](https://github.com/girder/large_image) to check whether the "New" annotation button should be shown in the image viewer.  Also prevents the access flag from appearing in the image viewer's individual annotation access control widget.
This PR should only be tested simultaneously with the [annotation-access-flag](https://github.com/girder/large_image/tree/annotation-access-flag) branch from girder/large_image and merged after it has been merged.
Closes #201
> Use new annotation creation access flag

- .circleci/config.yml
- histomicsui/web_client/panels/AnnotationSelector.js
- histomicsui/web_client/templates/panels/annotationSelector.pug
Follow up to #222 
The new large image release used in #222, uses a MongoDB operation added in Mongo version 4.4, however CI currently uses Mongo version 4.  This led #222 to periodically fail the `panelLayoutSpec.js` test upon merging, so this PR updates CI to use Mongo 4.4.
In addition, fixing this revealed that `panelLayoutSpec.js` was also failing because the rest request made to facilitate use of the new access flag endpoint was causing too much of a delay; this led `_orderPanels()` in `ImageView.js` to occasionally not display the annotation panel properly as directed by the plugin settings.  So this PR also moves the request such that the annotation panel can be rendered prior to the request being completed.
> Fix issue with panel layout from new access flag use (PR #222)

- histomicsui/web_client/panels/AnnotationSelector.js
This does some bookkeeping to ensure that quickly changing images still does the right thing.
> Reduce how often the new annotation button updates

- histomicsui/web_client/views/View.js
Before, it worked the first time but not necessarily subsequent times.
> Harden not closing modals when the mouse is dragged outside of it

- histomicsui/web_client/dialogs/saveAnnotation.js
- histomicsui/web_client/panels/MetadataPlot.js
- histomicsui/web_client/panels/MetadataWidget.js
- histomicsui/web_client/stylesheets/dialogs/saveAnnotation.styl
- histomicsui/web_client/templates/dialogs/saveAnnotation.pug
- histomicsui/web_client/templates/panels/metadataWidget.pug
- histomicsui/web_client/views/body/ImageView.js
This is shown in the annotation edit panel:
The metadata is stored in the annotation.attributes as per the schema.
A logical extension to this would be to show annotation metadata on the item page in some manner.
> Support annotation metadata

- histomicsui/web_client/stylesheets/body/image.styl
This increase the bottom padding to make it more obvious that the end of the panel was reached.
> Minor tweak to panel zone css.

- histomicsui/handlers.py
- setup.py
download returns a forward on S3 assetstores.
> Use open.read rather than download to access files in Girder.

- histomicsui/__init__.py
- histomicsui/rest/system.py
- tox.ini
Add some functions to facilitate assetstore maintenance.  You can check or prune abandoned files on an fs assetstore, and change the import path on a file on an fs assetstore.
Fix testing with tox 4.
> Assetstore maintenance

- docs/controls.rst
- histomicsui/web_client/panels/AnnotationSelector.js
- histomicsui/web_client/templates/panels/annotationSelector.pug
- histomicsui/web_client/views/body/ImageView.js
Also allow clearing the selection and add a few hotkeys.  By default, don't show the context menu after selection (it can be shown by right-click or hotkey).  Add a flag to show the context menu immediately after selecting a region of elements.
> Allow selecting elements by polygon

- histomicsui/web_client/dialogs/saveAnnotation.js
- histomicsui/web_client/panels/AnnotationSelector.js
- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/stylesheets/dialogs/saveAnnotation.styl
- histomicsui/web_client/templates/dialogs/saveAnnotation.pug
This still needs (a) categoric support, (b) palettes, (c) docs, (d) line width adjustment, (e) popover showing values, (f) tests.  Palettes would switch from specifying min/max color to min/max transparency.
This can use some geometric features of annotations, or takes values from annotation elements' `user` field.  For example, `"user": {"key1": 1.23, "key2": {"key3": 4.56}}` would offer styling for `key1` or `key2 - key3`.
> Color annotations by metadata.

- .circleci/config.yml
- histomicsui/rest/image_browse_resource.py
Use the .large_image_config.yaml file's itemList.defaultSort when determining the next and previous images.
This will have no effect unless a version of large_image with https://github.com/girder/large_image/pull/1099 is available.
> Apply configurable sort to next and previous images

- histomicsui/__init__.py
When restricting downloads, the POST resource/download endpoint had the wrong scope
> Fix a download scope issue

- histomicsui/web_client/stylesheets/popover/annotationPopover.styl
- histomicsui/web_client/templates/popover/annotationPopoverMetadata.pug
- histomicsui/web_client/views/popover/AnnotationPopover.js
The metadata on an element's user property only appears if it is associated with a top level key and has a value that is a string or a number.  Numbers are limited in precision to six digits.
A future improvement would be to show metadata based on the config file, including styling based on datatype information.
> Add annotation element metadata to the popover.

- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/templates/panels/drawWidgetElement.pug
When annotation group counts changed, the group selection option would vanish.
> Fix an issue with the select control update

- histomicsui/rest/system.py
- histomicsui/web_client/main.js
- histomicsui/web_client/stylesheets/views/searchResultsView.styl
- histomicsui/web_client/views/searchResultsView.js
- tox.ini
If you have multiple resources with the same name, the search page wasn't useful.
> Show resource paths in girder search pages.

- histomicsui/__init__.py
- histomicsui/constants.py
- histomicsui/handlers.py
If there are no requests that require a user id for around the specified duration, the user will be logged out.
This uses the `histomicsui.login_session_expiry_minutes` setting.  If that is non-zero and not None, the short sessions will be invoked.  This can be configured, as with any Girder settings, via the `GIRDER_SETTING_HISTOMICSUI_LOGIN_SESSION_EXPIRY_MINUTES` environment variable.
> Support short login sessions.

- histomicsui/web_client/views/body/ImageView.js
> Don't show the context menu when finishing an annotation.

- histomicsui/web_client/stylesheets/layout/layout.styl
This changes the z-index and position of the second region control's drop down button so it doesn't cover the first region control's drop down menu, an issue raised [here](https://github.com/girder/slicer_cli_web/issues/236)
> Adjust position and z-index of region control dropdown

- histomicsui/web_client/panels/MetadataPlot.js
This happens if the number of distinct values is longer with adjacent items
> Fix an issue with the distinct plottable list color

- histomicsui/web_client/panels/MetadataPlot.js
- histomicsui/web_client/templates/dialogs/metadataPlot.pug
- histomicsui/web_client/templates/panels/metadataPlot.pug
Restrict to a reasonable number of significant figures.
Always show name and annotation name when there are multiples.
Show bounding box region thumbnails in the plot hover box.
Reflect selections on the plot on annotation elements and vice versa.
> Improve plots

- histomicsui/web_client/panels/MetadataPlot.js
In many instances this will prevent overflow.  Plotly doesn't support sensible overflow or wrapping, so this is an alternative.
> Limit length of text in hover info on plots

- histomicsui/web_client/stylesheets/layout/headerAnalyses.styl
- histomicsui/web_client/templates/layout/headerAnalyses.pug
- histomicsui/web_client/views/layout/HeaderAnalysesView.js
This should now handle any analysis menu that doesn't have more versions than the screen height or names longer than some maximum.
> Better handle long analyses menu

- histomicsui/web_client/dialogs/metadataPlot.js
- histomicsui/web_client/panels/MetadataPlot.js
- histomicsui/web_client/stylesheets/dialogs/metadataPlot.styl
- histomicsui/web_client/stylesheets/panels/metadataPlot.styl
- histomicsui/web_client/templates/dialogs/metadataPlot.pug
- histomicsui/web_client/templates/panels/metadataPlot.pug
Allow adjusting multi-select size.  Show loading spinner.  Don't send needless compute requests.
> Improve plot dialog and options

- histomicsui/web_client/panels/MetadataPlot.js
Fix colors on multi-value violin plots.
> Fix maximizing the plot.

- histomicsui/web_client/dialogs/editElement.js
- histomicsui/web_client/dialogs/editStyleGroups.js
- histomicsui/web_client/dialogs/saveAnnotation.js
- histomicsui/web_client/package-lock.json
- histomicsui/web_client/package.json
- histomicsui/web_client/stylesheets/dialogs/editStyleGroups.styl
- histomicsui/web_client/templates/dialogs/editElement.pug
- histomicsui/web_client/templates/dialogs/editStyleGroups.pug
- histomicsui/web_client/templates/dialogs/saveAnnotation.pug
This PR adds a dependency on https://github.com/eastdesire/jscolor to replace the bootstrap colorpicker. The style is different from the old colorpicker but supports an alpha channel. Colors can be input via the widget or the input field using either hex or rgb(a).
> Move away from bootstrap colorpicker

- histomicsui/web_client/package-lock.json
- histomicsui/web_client/package.json
- histomicsui/web_client/views/layout/HeaderAnalysesView.js
Due to how the `bootstrap-submenu` plugin adds functionality to jQuery, it does not install itself properly on `girder.$`. This PR adds an additional import of `$ from 'jquery`, so that we can correctly initialize the dropdown menus with the plugin.
The downside is that now this view maintains two different instances of jquery (`$` and `girder.$` as `_$`).
I looked for other packages that could offer additional functionality, but could not find any that were relatively plug and play. Ideally we'd not want to rewrite much code or implement complex UI logic to hold up release of Girder 5. I came across libraries like popper.js and Floating UI, which provide tools for positioning UI elements, but it seemed like those weren't good fits for this.
I considered forking the `bootstrap-submenu` …
> Add submenu plugin to correct jQuery

- docs/config_options.rst
- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/views/body/ImageView.js
This adds the infrastructure to let hotkeys do other actions, too.
From a control standpoint, the hotkey will be ignored if it cannot be applied (e.g., if you aren't editing annotations, you switch groups via hotkey).  We could also want the hotkeys to apply more places (e.g., a group hotkey could change the group of the annotation under the cursor).
> Support configurable hotkeys to select annotation groups

- .circleci/config.yml
- .circleci/get_version.py
- .circleci/publish_pypi.sh
- MANIFEST.in
- setup.py
- tox.ini
This draws inspiration from the [script](https://github.com/girder/large_image/blob/dc21aeabf1f0f77ef233bd6fd9f8c963e9ebcf2a/.circleci/release_pypi.sh#L7-L13) used to publish large image, with some differences.
I intend to manually create tag `v2.0.0a1` on the `girder-5` branch before this is merged. On merge I expect `v2.0.0a2` to be created automatically.
> Run release job on girder-5

- histomicsui/web_client/dialogs/saveAnnotation.js
- histomicsui/web_client/panels/AnnotationSelector.js
- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/views/body/ImageView.js
- histomicsui/web_client/views/popover/AnnotationContextMenu.js
We really should never use silent.  This removes its use in annotation elements.
> Use an option flag rather than silent in some bootstrap calls

- histomicsui/web_client/panels/DrawWidget.js
Debounce this, so we only render once when we are all ready
> When updating the style groups, we would render the draw panel a lot

- histomicsui/web_client/panels/DrawWidget.js
- histomicsui/web_client/views/popover/AnnotationContextMenu.js
When setting the group from the context menu on a large number of annotation elements, we were refreshing the draw widget once per element instead of once at the end.
> Speed up bulk setting style groups

- histomicsui/web_client/templates/layout/headerAnalyses.pug
- histomicsui/web_client/views/layout/HeaderAnalysesView.js
When an analysis task is from a source other than docker hub, the container registry is often added as part of its name which makes it long.  Remove it from the Analysis drop down menu display if it remains unique.
> Shorten analysis menu entries when unambiguous

- histomicsui/web_client/stylesheets/panels/annotationSelector.styl
- histomicsui/web_client/stylesheets/panels/drawWidget.styl
- histomicsui/web_client/templates/panels/annotationSelector.pug
- histomicsui/web_client/templates/panels/drawWidgetElement.pug
When annotations have been loaded enough, the first element that has fill color, line color, or line width information is used to show the style of that group.  For individual annotations, this is also shown with the group counts.  As part of this, the count area has been refactored slightly to prevent long group names from making the marquee selector tool from becoming unreachable.
> Add annotation legends

- .circleci/config.yml
- .pre-commit-config.yaml
- setup.py
- tox.ini
It is EOL in a few weeks and is getting harder to test with pkg_resources deprecation.
> Drop Python 3.9
